export { default as logoDefault } from '/images/logoDefault.svg';
export { default as logoLight } from '/images/logoLight.svg';
export { default as hashTag } from '/images/hashTag.svg';
export { default as guy } from '/images/guy.png';
export { default as dots} from '/images/Dots.svg';
export { default as kavichki } from '/images/kavichki.svg';
export { default as about } from '/images/aboutImg.svg';
export { default as discord } from '/images/Discord.svg';
export { default as email } from '/images/Email.svg';
export { default as menu } from '/images/menu.svg';
export { default as burger } from '/images/burger.svg';
export { default as cross } from '/images/cross.svg';
